keto:
  automigration:
    enabled: true

  dev: false

  config:
    #DSN will be set via --set during deployment

    namespaces:
      - id: 0
        name: reports
        # Define relation types for reports namespace
        # owner: full access (view, delete, share)
        # viewer: read-only access (view)
      - id: 1
        name: admin
    
    serve:
      read:
        port: 4466
      write:
        port: 4467
      
    log:
      level: debug

service:
  read:
    enabled: true
    type: ClusterIP
    port: 4466
  write:
    enabled: true
    type: ClusterIP
    port: 4467