keto:
  automigration:
    enabled: true

  dev: false

  config:
    #DSN will be set via --set during deployment
    
    namespaces:
      - name: Report
        id: 1
    
    serve:
      read:
        port: 4466
      write:
        port: 4467
      
    log:
      level: debug

service:
  read:
    enabled: true
    type: ClusterIP
    port: 4466
  write:
    enabled: true
    type: ClusterIP
    port: 4467