apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: geometrics-protected
  namespace: geo-ory
spec:
  upstream:
    url: "http://ory-frontend.geo-ory.svc.cluster.local:80"
  match:
    url: <https:\/\/geometrics\.combaldieu\.fr.*>
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
  authenticators:
    - handler: cookie_session  # Requires Kratos login
  authorizer:
    handler: keto_engine_acp_ory
    config:
      required_action: "access"
      required_resource: "geometrics"
  mutators:
    - handler: noop
  errors:
    - handler: redirect
      config:
        to: https://kratos.combaldieu.fr/self-service/login/browser?return_to={{ .Request.URL.String }}