apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: geometrics-protected
  namespace: geo-ory
spec:
  upstream:
    url: "http://frontend.geo-metrics.svc.cluster.local:3000"
  match:
    url: <https:\/\/geometrics\.combaldieu\.fr\/(?!api\/).*>
    methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
  authenticators:
    - handler: cookie_session  # Requires Kratos login
  authorizer:
    handler: allow
  mutators:
    - handler: noop